### ISSUE TITLE
in project list, title and desc should be editable

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/scenevr-author#16]

**Comment by JoeGermuska** [comment]
@zachwise I am not sure I agree anymore. I think there's benefit/logic to having the entire project unit trigger editing.  Also, description doesn't even show in the project list right now. I think leaving each item in the list as a big "edit button" is good UX, especially for mobile.  

What do you think?

**Comment by zachwise** [comment]
I agree
