### ISSUE TITLE
refactor storage path handling

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/scenevr-author#24]
Places in the code that do inline logical handling of environment-specific storage paths are not ideal. We do this for constructing paths to images and embed code paths. This responsibility should be pushed into the storage class so that it is relatively abstracted away from the API code.

**Comment by JoeGermuska** [comment]
The immediate and simplest fix for this is to just make `AWS_STORAGE_BUCKET_URL` include the prefix. Yes, it's technically then not the "bucket" URL, but otherwise, it aligns with all of the code.
