### ISSUE TITLE
Image (scene) deleting is broken

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/scenevr-author#26]
I started to fix an apparent bug where one couldn't delete the final scene in a project. I accidentally pushed a partial fix which now prevents deleting any scenes.

**Comment by zachwise** [comment]
Getting this from the server `Ajax Error: <class 'KeyError'> 'sceneUUID'` if that helps.

**Comment by JoeGermuska** [comment]
@zachwise your comment referred to the partial fix I accidentally pushed. i was working on this while you reported it. AFAICT it is no longer an issue.
