### ISSUE TITLE
after re-ordering, editing scene caption selects wrong scene

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/scenevr-author#28]
For some reason, the click handler for editing a scene references the UUID of the scene which was in a given position on page load, even after re-ordering.

That is, if you load a project, drag the first scene to the second position, and then click the scene you just dragged, the UI will request from the server details for the scene which was originally in the second position.

The workaround is to go back to the project list and return - the re-rendered page will trigger the editor for the correct scene now.

**Comment by zachwise** [comment]
Running fetchPhotos after reorder might fix this

**Comment by JoeGermuska** [comment]
probably. but looking at this shows an inconsistency between counting on react state management and old-fashioned DOM inspection which feels like it could be a liability later. I'm going to take a little time to see if I can normalize that.

**Comment by JoeGermuska** [comment]
so I still don't understand why we are carting the title/description values from the DOM instead of treating them as state, but that was a dead end. Watching the values showed that something (presumably the Sortable library) was mutating the state of the scenes so that the UUID of the image stayed with the position instead of "moving" with the image. It kinda makes sense to me, and the UUID isn't actually mutable, so I moved it to props and fixed the bug.
